name: nodelab_movie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-28.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  responsive_sizer: ^3.1.1
  connectivity_plus: ^5.0.2
  lottie: ^2.2.0
  json_annotation: ^4.8.0
  flutter_dotenv: ^5.1.0
  easy_localization: ^3.0.1
  logger: ^2.6.1
  font_awesome_flutter: ^10.8.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  provider: ^6.1.5
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/app/.env

flutter_native_splash:
  fullscreen: true
  background_image: assets/images/splash.png
  android: true
  ios: true

